### ISSUE TITLE
Question about executing project

### ISSUE THREAD

**Issue by taehyun9203** [BeneficialCode/syzkaller-win#1]
Hi, I want to run your project in windows.

I try to execute your project by using the manual from your project and original syzkaller.

However, I failed to execute it.

I did this command from original syzkaller

`make fuzzer execprog stress TARGETOS=windows`

I attempted to execute this command from your project but made compile error.

I did this command by replacing executor folder from your project by using cl compiler in native tools command.

`cl executor\executor.cc /EHsc -o bin\windows_amd64\syz-executor.exe kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib winmm.lib rpcrt4.lib Crypt32.lib imm32.lib Urlmon.lib Oleaut32.lib Winscard.lib Opengl32.lib Mpr.lib Ws2_32.lib Bcrypt.lib Ncrypt.lib Synchronization.lib Shell32.lib Rpcns4.lib Mswsock.lib  Mincore.lib Msimg32.lib RpcRT4.lib Rpcrt4.lib lz32.lib`

I am stuck in this step.

`bin\windows_amd64\syz-stress.exe -executor c:\full\path\to\bin\windows_amd64\syz-executor.exe`

I wonder how to execute your project precisely.

Would you explain?

**Comment by BeneficialCode** [comment]
Below is a test command: 
`syz-stress.exe -executor=syz-executor.exe -logprog true`

**Comment by taehyun9203** [comment]
Hi, Thank you for answering my question :)

I faced another problem when I command `syz-stress.exe -executor=syz-executor.exe -logprog true`

```
2023/02/01 05:38:15 unsupported syscall: NeedCurrentDirectoryForExePathA: not in set of enabled calls
2023/02/01 05:38:15 unsupported syscall: OpenDriver: not in set of enabled calls
2023/02/01 05:38:15 unsupported syscall: timeKillEvent: not in set of enabled calls
2023/02/01 05:38:15 unsupported syscall: CertRegisterSystemStore: not in set of enabled calls
2023/02/01 05:38:15 unsupported syscall: FillPath: not in set of enabled calls
2023/02/01 05:38:15 unsupported syscall: GetUserDefaultLangID: not in set of enabled calls
2023/02/01 05:38:15 unsupported syscall: ImmEnumInputContext: not in set of enabled calls
2023/02/01 05:38:15 unsupported syscall: NCryptGetProperty: not in set of enabled calls
2023/02/01 05:38:15 unsupported syscall: RpcErrorGetNumberOfRecords: not in set of enabled calls
2023/02/01 05:38:15 unsupported syscall: RpcSmSetClientAllocFree: not in set of enabled calls
2023/02/01 05:38:15 unsupported syscall: SetThreadDesktop: not in set of enabled calls
2023/02/01 05:38:15 unsupported syscall: CharNextExA: not in set of enabled calls
2023/02/01 05:38:15 unsupported syscall: GetMouseMovePointsEx: not in set of enabled calls
2023/02/01 05:38:15 unsupported syscall: Wow64RevertWow64FsRedirection: not in set of enabled calls
panic: no syscalls enabled and generatable

goroutine 1 [running]:
github.com/google/syzkaller/prog.(*Target).BuildChoiceTable(0xc0000c96c0, {0x0, 0x12, 0x0}, 0x1)
        /home/test/syzkaller/prog/prio.go:212 +0x89b
main.main()
        /home/test/syzkaller/tools/syz-stress/stress.go:83 +0x3d6

C:\Users\user\Desktop\syzkaller\bin\windows_amd64>
```
![image](https://user-images.githubusercontent.com/41182842/215962420-8fd90a6b-0100-4f32-82f9-c7e4a640d4b5.png)

![image](https://user-images.githubusercontent.com/41182842/215960856-bad10143-a59d-4225-9a80-e9bf861e771a.png)

Could you give me any advice about this error?

I think this error is related to config file.

I cannot make the config file in the second picture in your project. (config.cfg)

**Comment by BeneficialCode** [comment]
Syz-stress just a test tool. It uses --syscalls to enable syscall sets. You should choose some syscall, then pass it to syz-stress.exe.
`syz-stress.exe -executor=syz-executor.exe -syscalls CreateFileA -logprog true`

**Comment by taehyun9203** [comment]
Hi, I passed your command `syz-stress.exe -executor=syz-executor.exe -syscalls CreateFileA -logprog true`

![image](https://user-images.githubusercontent.com/41182842/215968007-61c246cf-106d-4fad-8865-281087dbb307.png)

It looks like it's being executed to me, is this the right execution?

**Comment by BeneficialCode** [comment]
I don't know. It seems that you are fuzzing the GetWindowRgn now, but my command's syscall is CreateFileA.

**Comment by taehyun9203** [comment]
Ah yes, I ran the system call.

Would I ask something more?

I wonder how to make config.file in windows O/S

I think you made config.file in your project. (based on picture in your project)

How did you do that?

In contrast to Linux, windows do not offer kernel source code and I did not have any idea to make config.file.

Could you give me some advice on that?
